import type { Metadata } from "next";
import "./globals.css";

import useMediaQuery from "@mui/material/useMediaQuery";
import React from "react";
import Header from "./_PageComponents/Header";
// import { MobileHeader } from "./_PageComponents/MobileHeader";

export const Mobile = ({ children }: { children: React.ReactNode }) => {
  const isMobile = useMediaQuery("(max-width:743px)");
  return isMobile ? children : null;
};
export const Desktop = ({ children }: { children: React.ReactNode }) => {
  // const isDesktop = useMediaQuery("(min-width:744px)");
  const isDesktop = true;
  return isDesktop ? children : null;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*<Desktop>*/}

      {/*</Desktop>*/}
      {/*<Mobile>
        <MobileHeader />
  </Mobile>*/}
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
