import { UserForm } from "./UserType";
export type Post = {
  id: string;
  version: number;
  key: number;
  image_id: string[];
  title: string;
  basic_info: string;
  price: number;
  description: string;
  position: string;
  rule: string;
  refund_policy: string;
  benefit: string;
  extra_info: string;
  start_day: Date;
  end_day: Date;
  min_duration: number;
  max_duration: number;
  postuser_id: string;
  postuser: UserForm;
  deleted: boolean;
  post_date: Date;
  private: boolean;
  request: boolean;
  limit_people: number;
  number_room: number;
  number_bathroom: number;
  number_bedroom: number;
  accomodation_type: string; //건물 유형
  building_type: string; //아파트인지, 주택인지
  contract: boolean;
  Reservation: Reservation[];
  x_coordinate: number;
  y_coordinate: number;
  city: string;
  gu: string;
  dong: string;
  street: string;
  street_number: string;
  post_code: string;
  local_save: boolean;
  ChatRoom: ChatRoom[];
  RequestForm: RequestRoom[];
  requestIDs: string[];
  like_count: number;
  like_user_id: string[];
  like_user: UserForm[];
};
